demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myaccounts.urls')),
]

myaccounts/urls.py
from django.urls import path
from . import views

app_name = 'myaccounts'

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.registration_view, name='signup'),
]

myaccounts/models.py
from django.db import models

# Create your models here.

myaccounts/forms.py
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model
)

User = get_user_model()


class MyUserLoginForm(forms.Form):
    username = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control mt-5',
            'autofocus': '',
            'style': 'width:66ch',
            'placeholder': 'Enter username...',
        }
    ), )

    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter password...',
        }
    ), )

    # https://docs.djangoproject.com/en/2.1/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError(
                    'Oh! I can\'t find that user - create user first!')
            elif not user.check_password(password):
                raise forms.ValidationError(
                    'Oh! That password is incorrect - try again!')
            elif not user.is_active:
                raise forms.ValidationError(
                    'Oh! That user is not active in the database!')


class MyUserRegistrationForm(forms.ModelForm):
    username = forms.CharField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control mt-5',
            'autofocus': '',
            'style': 'width:66ch',
            'placeholder': 'Enter username...',
        }
    ), )
    email1 = forms.EmailField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Email Address...',
        }
    ), )
    email2 = forms.EmailField(label='', widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Confirm Email Address...',
        }
    ), )
    password = forms.CharField(label='', widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Enter password...',
        }
    ), )

    class Meta:
        model = User
        fields = ['username', 'email1', 'email2', 'password', ]

    # https://docs.djangoproject.com/en/2.1/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
    def clean(self):
        super().clean()
        email1 = self.cleaned_data.get('email1')
        email2 = self.cleaned_data.get('email2')
        if email1 != email2:
            raise forms.ValidationError('Email addresses must match!')
        email_qs = User.objects.filter(email=email1)
        if email_qs.exists():
            raise forms.ValidationError('Email address already registered!')

myaccounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import MyUserLoginForm, MyUserRegistrationForm

from django.contrib.auth import (
    authenticate,
    login,
    logout,
)


# Create your views here.
@login_required(login_url='myaccounts:login')
def home(request):
    return render(request, 'myaccounts/home.html', {})


def login_view(request):
    next = request.GET.get('next')
    form = MyUserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect('myaccounts:home')
    return render(request, 'myaccounts/login.html', {'form': form})


def registration_view(request):
    if not request.user.is_authenticated:
        next = request.GET.get('next')
        form = MyUserRegistrationForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data.get('password')
            email = form.cleaned_data.get('email1')
            user.set_password(password)
            user.email = email
            user.save()
            new_user = authenticate(username=user.username, password=password)
            login(request, new_user)
            if next:
                return redirect(next)
            return redirect('myaccounts:home')
        return render(request, 'myaccounts/signup.html', {'form': form})
    else:
        return redirect('myaccounts:home')


@login_required(login_url='myaccounts:login')
def logout_view(request):
    logout(request)
    return redirect('myaccounts:home')

myaccounts/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="description" content="Custom Login Application by Aniket Aryamane">
    <meta name="author" content="Aniket Aryamane">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>{% block title %}{% endblock %}</title>
    <link rel="apple-touch-icon" href="">
    {% load static %}

    <!-- Link to Bootstrap CSS file -->
    <link rel="stylesheet" href="{% static 'myaccounts/css/vendor/bootstrap/bootstrap.min.css' %}" type="text/css">

    <!-- Link to Materialize CSS file -->
    <!-- <link rel="stylesheet" href="{% static 'myaccounts/css/vendor/materialize/materialize.min.css' %}" type="text/css"> -->

    <!-- Link to your favicon.ico file -->
    <link rel="shortcut icon" href="{% static 'myaccounts/img/favicon.ico' %}" type="image/x-icon">

    <!-- Link to your css file -->
    <link rel="stylesheet" href="{% static 'myaccounts/css/main.css' %}" type="text/css">

</head>

<body>
<div class="container">
    {% block content %}{% endblock %}
</div>


<!-- Link to Materialize JS file -->
<!-- <script src="{% static 'myaccounts/js/vendor/materialize/materialize.min.js' %}"></script> -->

<!-- JQuery comes first in the list -->
<script src="{% static 'myaccounts/js/vendor/bootstrap/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'myaccounts/js/vendor/bootstrap/popper.min.js' %}"></script>
<script src="{% static 'myaccounts/js/vendor/bootstrap/bootstrap.min.js' %}"></script>

<!-- Link to your js file -->
<script src="{% static 'myaccounts/js/main.js' %}"></script>
</body>

</html>

myaccounts/templates/myaccounts/home.html
{% extends 'layout.html' %}

{% block title %}
    MyAccounts | Home
{% endblock %}

{% block content %}
    <h1 class="text-center">Home</h1>
{% endblock %}

myaccounts/templates/myaccounts/login.html
{% extends 'layout.html' %}

{% block title %}
    MyAccounts | Login
{% endblock %}

{% block content %}
    <div class="font-weight-normal text-center mt-5">
        <h2 class="font-weight-normal">Please sign in...</h2>
        <img src="https://via.placeholder.com/80x80" alt="" class="mt-1"/>
    </div>
    <div class="d-flex justify-content-center align-items-center mt-5" style="height: 200px;">
        <form action="{% url 'myaccounts:login' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-lg btn-primary mt-4" style="width: 100%;"
                   value="Sign in"/>
            <p class="mt-2 text-muted text-center">&copy; 2017-2018</p>
        </form>
    </div>
{% endblock %}

myaccounts/templates/myaccounts/signup.html
{% extends 'layout.html' %}

{% block title %}
    MyAccounts | Register
{% endblock %}

{% block content %}
    <div class="font-weight-normal text-center mt-5">
        <h2 class="font-weight-normal">Please sign up...</h2>
        <img src="https://via.placeholder.com/80x80" alt="" class="mt-1"/>
    </div>
    <div class="d-flex justify-content-center align-items-center mt-5" style="height: 350px;">
        <form action="{% url 'myaccounts:signup' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-lg btn-primary mt-4" style="width: 100%;"
                   value="Sign up"/>
            <p class="mt-2 text-muted text-center">&copy; 2017-2018</p>
        </form>
    </div>
{% endblock %}